name: nsf6

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://nsf6:yourpassword@postgre:5432/nsf6_db
    depends_on:
      - postgre
      
  postgre:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nsf6
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=nsf6_db
    ports:
      - "5432:5432"

volumes:
  db_data: