services:
  postgre:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nsf6
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=nsf6_db
    ports:
      - "5432:5432"

volumes:
  postgre: